prefer-workspace-packages: true
packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@umijs/yorkie': true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  mime: true
  puppeteer-core: true
overrides:
  supersonic-chat-sdk: link:packages/chat-sdk
